/*Department Table*/
select * from DEPT

SELECT * FROM DEPT WHERE DEPTNO = 20;

SELECT DNAME, LOC FROM DEPT;

UPDATE DEPT SET LOC = 'CHICAGO' WHERE DEPTNO = 30;

DELETE FROM DEPT WHERE DEPTNO = 40;

INSERT INTO DEPT (DEPTNO, DNAME, LOC) VALUES (40, 'OPERATIONS', 'BOSTON');

DELETE FROM dept WHERE deptno = 50;

/*Employee Table*/
SELECT * FROM EMP;

SELECT * FROM EMP WHERE JOB = 'MANAGER';

SELECT * FROM EMP WHERE SAL > 2500;

SELECT * FROM EMP WHERE HIREDATE > '1981-06-01';

SELECT EMP.*, DEPT.DNAME, DEPT.LOC FROM EMP INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO;

SELECT DEPT.DEPTNO, DEPT.DNAME, SUM(EMP.SAL) AS TOTAL_SALARY
FROM EMP
INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
GROUP BY DEPT.DEPTNO, DEPT.DNAME;



